FROM alpine:3.11

# Copy
COPY srcs/nginx.conf srcs/index.html srcs/start.sh ./
COPY srcs/ssl/localhost.pem localhost.pem
COPY srcs/ssl/localhost-key.pem localhost-key.pem

# Install nginx and dependencies
RUN apk update && \
	apk add --no-cache nginx openssh openssl

# Setup nginx
RUN mkdir -p /run/nginx www && \
	mv nginx.conf /etc/nginx/ && \
	mv index.html /www/

# # Setup SSL
# RUN openssl req -new -newkey rsa:2048 -nodes -days 365 -x509 \
# 	-subj "/C=FR/ST=IDF/L=Paris/O=42/OU=Federation/CN=localhost" \
# 	-keyout /etc/ssl/private/services.key -out /etc/ssl/certs/services.crt

# Setup SSH
RUN ssh-keygen -A && \
	adduser -D admin && \
	echo "admin:password" | chpasswd

# Telegraf
RUN mkdir /etc/telegraf
COPY srcs/telegraf-1.15.3.tar.gz .
COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf
RUN tar -zxvf telegraf-1.15.3.tar.gz
RUN rm telegraf-1.15.3.tar.gz


EXPOSE 22 80 443

CMD ./start.sh