FROM alpine:latest

# GENERAL
RUN apk update
RUN apk add nginx bash openrc --no-cache


# SSH - Downloadnig open ssh
RUN apk add openssh 
# SSH - Using custom config with port 22
COPY srcs/ssh/sshd_config.conf /etc/ssh/sshd_config

# NGINX - installs things
COPY srcs/default.conf etc/nginx/conf.d/default.conf
COPY srcs/proxy.conf etc/nginx/conf.d/proxy.conf
# COPY srcs/index.html /usr/share/nginx/html/index.html


# SSL - priv key
COPY srcs/ssl/localhost.pem localhost.pem
# SSL - pub key
COPY srcs/ssl/localhost-key.pem localhost-key.pem


# General - entrypoint
COPY srcs/start.sh /start.sh

EXPOSE 80 443 22

ENTRYPOINT sh /start.sh