FROM alpine:latest

RUN apk update

# rc-service
RUN apk add openrc --no-cache
RUN apk add nginx

# root location
RUN mkdir -p /var/www/html/
RUN chown -R nginx:nginx /var/www/html


RUN mkdir -p /run/nginx

ADD srcs/nginx.conf /etc/nginx/conf.d/default.conf

ADD srcs/script.sh /var/script.sh
EXPOSE 80 443

RUN chmod +x /var/script.sh
#ENTRYPOINT ["sh", "/var/start.sh"]

