FROM alpine:3.11

ARG MINIKUBE_IP

RUN apk update && \
	apk add nginx && \
	apk add mysql-client && \
	apk add jq && \
	apk add curl && \
	apk add php7 php7-fpm php7-opcache php7-common php7-curl php7-json php7-mbstring php7-xml php7-zip php7-gd php7-soap php7-tokenizer php7-dom php7-exif php7-fileinfo php7-mysqli php7-zlib php7-phar

# stuff
COPY srcs/nginx/default.conf /etc/nginx/nginx.conf
COPY setup.sh /
RUN chmod +x /setup.sh

# Ownership
RUN adduser -D -g 'www' www && \
	mkdir /www && \
	mkdir /var/run/nginx && \
	chown -R www:www /var/lib/nginx && \
	chown -R www:www /www

# Wordpress cli
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod 777 wp-cli.phar
RUN	chmod +x /www
RUN mv wp-cli.phar /usr/local/bin/wp

# installing wp
RUN cd /www && wp core download

# Telegraf
RUN mkdir /etc/telegraf
COPY srcs/telegraf-1.15.3.tar.gz .
COPY srcs/telegraf.conf /etc/telegraf/telegraf.conf
RUN tar -zxvf telegraf-1.15.3.tar.gz
RUN rm telegraf-1.15.3.tar.gz

RUN echo $MINIKUBE_IP > ip.txt
EXPOSE 80
CMD ./setup.sh

